<!doctype html>
<html lang="fa" dir="rtl">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>ثبت سفارش آزمایشی | Etod Graphic</title>
    @vite(['resources/css/app.css', 'resources/js/app.js'])
</head>
<body class="min-h-screen bg-[#fbfaff] text-[#171326]">
    <header class="border-b border-[#eeeaf5] bg-white"><div class="mx-auto flex h-20 max-w-7xl items-center justify-between px-5 lg:px-8"><a href="{{ route('home') }}" class="text-2xl font-black text-violet-700">Etod <span class="text-[#171326]">Graphic</span></a><a href="{{ route('cart.index') }}" class="font-bold text-violet-700">بازگشت به سبد</a></div></header>
    <main class="mx-auto max-w-5xl px-5 py-10 lg:px-8"><h1 class="text-4xl font-black">اطلاعات سفارش</h1><p class="mt-3 text-slate-600">این مرحله آزمایشی است و به درگاه واقعی متصل نیست.</p><div class="mt-8 grid gap-6 lg:grid-cols-[1fr_340px]"><form action="{{ route('checkout.store') }}" method="POST" class="rounded-3xl bg-white p-6 shadow-sm">@csrf<label class="block font-bold">نام و نام خانوادگی<input name="customer_name" value="{{ old('customer_name') }}" class="mt-2 w-full rounded-xl border border-[#e8e3f1] px-4 py-3" required></label>@error('customer_name')<p class="mt-1 text-sm text-red-500">{{ $message }}</p>@enderror<label class="mt-5 block font-bold">شماره موبایل<input name="customer_phone" value="{{ old('customer_phone') }}" placeholder="09123456789" dir="ltr" class="mt-2 w-full rounded-xl border border-[#e8e3f1] px-4 py-3 text-left" required></label>@error('customer_phone')<p class="mt-1 text-sm text-red-500">{{ $message }}</p>@enderror<label class="mt-5 block font-bold">آدرس<textarea name="customer_address" rows="4" class="mt-2 w-full rounded-xl border border-[#e8e3f1] px-4 py-3" required>{{ old('customer_address') }}</textarea></label>@error('customer_address')<p class="mt-1 text-sm text-red-500">{{ $message }}</p>@enderror<label class="mt-5 flex items-center gap-2 text-sm"><input type="checkbox" name="portfolio_consent" value="1" class="accent-violet-700">اجازه نمایش تصویر سفارش در نمونه‌کارها را می‌دهم.</label><button class="mt-7 w-full rounded-2xl bg-violet-700 px-5 py-4 font-black text-white shadow-lg shadow-violet-200">ایجاد سفارش آزمایشی</button></form><aside class="h-fit rounded-3xl bg-white p-6 shadow-sm"><h2 class="text-xl font-black">خلاصه سفارش</h2><div class="mt-6 space-y-3">@foreach($cart->items as $item)<div class="flex justify-between gap-3 text-sm"><span>{{ $item->variant->product->name }} × {{ $item->quantity }}</span><strong>{{ number_format($item->unit_price * $item->quantity) }}</strong></div>@endforeach</div><div class="mt-6 flex justify-between border-t border-[#eeeaf5] pt-5 font-black"><span>جمع کل</span><span class="text-violet-700">{{ number_format($totals['total']) }} ریال</span></div></aside></div></main>
</body>
</html>
